/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "thopytduqivltdgzqzlp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRob3B5dGR1cWl2bHRkZ3pxemxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1MjgzODksImV4cCI6MjA5MzEwNDM4OX0.v3N5uZ--lWYszxlfe1KWh7iUt2CcTP0_SP6rNlwf6Kk"